### ISSUE TITLE
Failed to resolve: cn.leancloud:leancloud-sdk:5.0.0

### ISSUE THREAD

**Issue by meixililu** [leancloud/java-sdk-all#15]
Gradle 配置
implementation 'cn.leancloud:storage-android:5.0.0'
implementation 'cn.leancloud:storage-android:5.0.1'
implementation 'cn.leancloud:storage-android:5.0.2'
都提示
Failed to resolve: cn.leancloud:leancloud-sdk:5.0.0

**Comment by meixililu** [comment]
cn.leancloud.convertor.ObserverBuilder这个类
todo.findInBackground().subscribe(ObserverBuilder.buildSingleObserver(new FindCallback<AVObject>() {}，我用这个修改了老代码，android提示是在主线程

**Comment by meixililu** [comment]
implementation 'cn.leancloud:storage-core:5.0.2' 用这个引入成功了，implementation 'cn.leancloud:storage-android:5.0.2'这个不行，总是提示Failed to resolve: cn.leancloud:leancloud-sdk:5.0.0

**Comment by jwfing** [comment]
使用错误，按照 [wiki](https://github.com/leancloud/java-sdk-all/wiki/0-Get-Started) 的接入方式来就可以了：

- 依赖
```
implementation('cn.leancloud:storage-android:5.0.1')
implementation 'io.reactivex.rxjava2:rxandroid:2.1.0'
implementation 'com.alibaba:fastjson:1.1.70.android'
```

- SDK 初始化
```
// 注意，这里要使用 storage-android 这个 lib 里面的 cn.leancloud.AVOSCloud 类的方法来初始化
public class MyLeanCloudApp extends Application {

    @Override
    public void onCreate() {
        super.onCreate();

        // 初始化参数依次为 this, AppId, AppKey
        AVOSCloud.initialize(this,"{your_appId}}","{your_appKey}");
    }
}
```
