### ISSUE TITLE
Failed to resolve: cn.leancloud:huawei-hmsagent:5.0.2

### ISSUE THREAD

**Issue by xfort** [leancloud/java-sdk-all#16]
android gradle 添加 混合推送时
implementation('cn.leancloud:mixpush-android:5.0.2')

报错Failed to resolve: cn.leancloud:huawei-hmsagent:5.0.2

**Comment by jwfing** [comment]
@xfort 这部分需要直接从这里拷贝源码加入工程里面。
这个 lib 是华为提供的，由我们来发布不太好，所以现在选择了源码的方式。

**Comment by xingchenxuanfeng** [comment]
@jwfing  那就从依赖关系里把这个依赖去掉啊，这样留着依赖，每个开发者都得手动去掉它

**Comment by xingchenxuanfeng** [comment]
@jwfing 或者提供一个华为的依赖地址也行啊
