### ISSUE TITLE
maven 仓库地址怎么配置？

### ISSUE THREAD

**Issue by otwayz** [leancloud/java-sdk-all#21]
我看你们的sample 使用的是 本地的仓库，那么你给我的maven仓库没有远程的配置么？

```
 //LeanCloud 的包仓库
        maven {
            url "http://mvn.leancloud.cn/nexus/content/repositories/public"
        }
```

这个地址并不能找到 storage-android:5.0.7 这个库，我查看了下 ，只有5.0.0-SNAPSHOT 版本

**Comment by otwayz** [comment]
@jwfing

**Comment by jwfing** [comment]
无须单独配置 maven 仓库，我们最新版本的都发到 jCenter() 对应的 repository 去了，你们应该都是可以直接使用的。
