### ISSUE TITLE
AVUser wiki 文档貌似有问题

### ISSUE THREAD

**Issue by otwayz** [leancloud/java-sdk-all#25]
AVUser.alwaysUseSubUserClass(subUser.class);
这个在文章末尾提到的要想返回的 AVUser 替换成自定义子类 需要设置的方法，貌似在Api中并没有提供

**Comment by otwayz** [comment]
@jwfing

**Comment by jwfing** [comment]
新版本确实去掉了这个方法，因为感觉它和其他方法是重复的。如果你们依赖于它，我们可以在下个版本加回来。
