### ISSUE TITLE
5.0.12添加了关闭缓存功能后，请勿创建目录PaasKeyValueCache并写入缓存file

### ISSUE THREAD

**Issue by funcfoo** [leancloud/java-sdk-all#41]
5.0.12添加了关闭缓存功能后，请勿创建目录PaasKeyValueCache并写入缓存file

**Comment by funcfoo** [comment]
如果真的是要做跨java android的sdk请分层写, 这样写会很难改, 很难用.
1. 异步独立
2. reactive独立
3. 缓存层独立

**Comment by jwfing** [comment]
如果要使用文件，就不能禁用缓存，因为可能文件大小是内存放不下的，所以如果是要禁用缓存，就不要使用文件功能。
