### ISSUE TITLE
Build.VERSION.SDK_INT小于23，context.checkSelfPermission全奔溃了

### ISSUE THREAD

**Issue by godwasdog** [leancloud/java-sdk-all#42]
@TargetApi(Build.VERSION_CODES.N)
  private static void startServiceIfRequired(Context context,
                                             final java.lang.Class<? extends android.app.Activity> cls) {
    if (isStarted) {
      return;
    }

    if (context == null) {
      LOGGER.d("context is null");
      return;
    }

    if (PackageManager.PERMISSION_GRANTED != context.checkSelfPermission("android.permission.INTERNET")) {

**Comment by godwasdog** [comment]
一定要minSdkVersion 23吗？

**Comment by jwfing** [comment]
这与 SDK 的版本没有关系吧，看样子是没有网络访问的权限导致的，这是推送或聊天最基本的权限，如果这个都不授权的话，这个服务就不可用了。
需要在 manifest 里面配置，详见文档：https://leancloud.cn/docs/android_push_guide.html#hash-1153434734

**Comment by godwasdog** [comment]
> 这与 SDK 的版本没有关系吧，看样子是没有网络访问的权限导致的，这是推送或聊天最基本的权限，如果这个都不授权的话，这个服务就不可用了。
> 需要在 manifest 里面配置，详见文档：https://leancloud.cn/docs/android_push_guide.html#hash-1153434734

并不是。怎么可能不给android.permission.INTERNET

**Comment by jwfing** [comment]
你好，realtime-android 5.0.12 版本已经发布，修复了这个问题。
